% !Hasselt IBK1E0
Pt=4227;
Pr=8422;
Pa=14992;
p=60;
lambda=1.38;
[idealBufferRound, ~, nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBK1E0.IdealBuffer = idealBufferRound;
idealBuffers.IBK1E0.nCoef = nCoef;
idealBuffers.IBK1E0.pCoef = pCoef;

% IBE0K1
Pt=1745;
Pr=0;
Pa=22515;
p=60;
lambda=5;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,1);
idealBuffers.IBE0K1.IdealBuffer = idealBufferRound;
idealBuffers.IBE0K1.nCoef = nCoef;
idealBuffers.IBE0K1.pCoef = pCoef;
% IBK1E1
Pt=121;
Pr=8422;
Pa=8422;
p=60;
lambda=1.38;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBK1E1.IdealBuffer = idealBufferRound;
idealBuffers.IBK1E1.nCoef = nCoef;
idealBuffers.IBK1E1.pCoef = pCoef;
% IBE0K0=
Pt=119;
Pr=0;
Pa=22515;
p=60;
lambda=5;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBE0K0.IdealBuffer = idealBufferRound;
idealBuffers.IBE0K0.nCoef = nCoef;
idealBuffers.IBE0K0.pCoef = pCoef;
% !Leuven
% IBC1E0=
Pt=0;
Pr=43423;
Pa=14474;
p=60;
lambda=1.62;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBC1E0.IdealBuffer = idealBufferRound;
idealBuffers.IBC1E0.nCoef = nCoef;
idealBuffers.IBC1E0.pCoef = pCoef;
% IBC1M0=
Pt=533;
Pr=43423;
Pa=14474;
p=60;
lambda=1.62;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBC1M0.IdealBuffer = idealBufferRound;
idealBuffers.IBC1M0.nCoef = nCoef;
idealBuffers.IBC1M0.pCoef = pCoef;
% IBM1C0=
Pt=394;
Pr=12151.5;
Pa=5554.5;
p=60;
lambda=5;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBM1C0.IdealBuffer = idealBufferRound;
idealBuffers.IBM1C0.nCoef = nCoef;
idealBuffers.IBM1C0.pCoef = pCoef;
% IBE1C0=
Pt=149;
Pr=26674.5;
Pa=7053.5;
p=60;
lambda=5;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBE1C0.IdealBuffer = idealBufferRound;
idealBuffers.IBE1C0.nCoef = nCoef;
idealBuffers.IBE1C0.pCoef = pCoef;
% !Aarschot
% IBM1E0=
Pt=980;
Pr=3002;
Pa=14992;
p=60;
lambda=2.31;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBM1E0.IdealBuffer = idealBufferRound;
idealBuffers.IBM1E0.nCoef = nCoef;
idealBuffers.IBM1E0.pCoef = pCoef;
% IBE1M0=
Pt=980;
Pr=19024;
Pa=4377;
p=60;
lambda=1.3;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBE1M0.IdealBuffer = idealBufferRound;
idealBuffers.IBE1M0.nCoef = nCoef;
idealBuffers.IBE1M0.pCoef = pCoef;
% !Landen
% IBC0K1=
Pt=4817;
Pr=0;
Pa=53623;
p=60;
lambda=1.62;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBC0K1.IdealBuffer = idealBufferRound;
idealBuffers.IBC0K1.nCoef = nCoef;
idealBuffers.IBC0K1.pCoef = pCoef;
% IBK0C1=
Pt=4817;
Pr=0;
Pa=5109;
p=60;
lambda=1.38;
[idealBufferRound, ~ , nCoef, pCoef] = calculateIdealBuffer(lambda,p,Pt,Pr,Pa,0);
idealBuffers.IBK0C1.IdealBuffer = idealBufferRound;
idealBuffers.IBK0C1.nCoef = nCoef;
idealBuffers.IBK0C1.pCoef = pCoef;